import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Montserrat,
  Nunito,
  Playfair_Display,
  Roboto,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair_display = Playfair_Display({
  weight: ["400", "500", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
  variable: "--font-playfair_display",
});

const montserrat = Montserrat({
  weight: ["300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
  variable: "--font-montserrat",
});

const nunito = Nunito({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext", "vietnamese"],
  variable: "--font-nunito",
});

const roboto = Roboto({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext", "vietnamese"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Summit Supply",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${playfair_display.variable} ${montserrat.variable} ${roboto.variable} ${nunito.variable} ${roboto.variable}`}
      >
        <div className="app">{children}</div>
      </body>
    </html>
  );
}
